# -*- coding: utf-8 -*-
"""OR Presentation-Cournot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EfP-WKQ078onmEQpZlLwkI2FetTPDyvs
"""

from scipy.optimize import fsolve

# Defining the equations
def equations(vars):
    q1, q2 = vars
    eq1 = (48.89 - 1.89 * q2) / 3.78 - q1
    eq2 = (48.89 - 1.89 * q1) / 3.78 - q2
    return [eq1, eq2]

# Initial guess
initial_guess = [0, 0]

# Solve the equations
q1, q2 = fsolve(equations, initial_guess)

print("Nash Equilibrium")
print(f"q1 = {q1}")
print(f"q2 = {q2}")